Repository NaKaLiGoBa/WebIDE, pull requests merged in 2023-10, with the labels that each got.

#102 96 re idepage project create modal UI 구현
  frontend/src/pages/IDEPage/components/file_explorer/INITIAL_TREE.jsx
  frontend/src/pages/IDEPage/components/file_explorer/TabSettings.jsx
  frontend/src/pages/IDEPage/components/file_explorer/index.jsx
  frontend/src/pages/IDEPage/components/modal/ModalMenu_Btn.css
  frontend/src/pages/IDEPage/components/modal/ModalMenu_Btn.jsx
  frontend/src/pages/IDEPage/components/modal/index.jsx
  frontend/src/pages/IDEPage/components/sidebar/index.jsx
  frontend/src/pages/IDEPage/index.jsx
  frontend/src/service/projectService.js
Labels: 💜 FE, 🌟 feat

#104 88 프로젝트 실행시키기
  backend/Dockerfile
  backend/app.prod.Dockerfile
  backend/app.test.Dockerfile
  backend/build.gradle
  backend/docker-compose.yaml
  backend/dockerfiles/java.Dockerfile
  backend/dockerfiles/node14.Dockerfile
  backend/dockerfiles/python3.Dockerfile
  backend/src/main/java/com/nakaligoba/backend/config/AwsConfig.java
  backend/src/main/java/com/nakaligoba/backend/config/SecurityConfig.java
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/domain/Language.java
  backend/src/main/java/com/nakaligoba/backend/domain/ProjectFile.java
  backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/mapper/FileMapper.java
  backend/src/main/java/com/nakaligoba/backend/entity/mapper/Mapper.java
  backend/src/main/java/com/nakaligoba/backend/filter/CorsFilter.java
  backend/src/main/java/com/nakaligoba/backend/repository/FileRepository.java
  backend/src/main/java/com/nakaligoba/backend/repository/MemberProjectRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/DockerTemplate.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
  backend/src/main/java/com/nakaligoba/backend/service/RunFileService.java
  backend/src/main/resources/api/file/file.yaml
  backend/src/main/resources/api/file/run.yaml
  backend/src/main/resources/api/project/save.yaml
  backend/src/main/resources/api/root.yaml
  backend/src/main/resources/application-test.yaml
  backend/src/main/resources/db/schema.sql
  backend/src/test/java/com/nakaligoba/backend/service/RunFileServiceTest.java
  docs/output.yaml
Labels: 💙 BE, 🌟 feat

#109 96 re idepage project create modal UI 구현
  frontend/package.json
  frontend/src/pages/IDEPage/components/file_explorer/TabSettings.jsx
  frontend/src/pages/IDEPage/components/file_explorer/index.jsx
  frontend/src/pages/IDEPage/components/modal/index.jsx
  frontend/src/service/apiUtils.js
  frontend/src/service/projectService.js
Labels: 💜 FE

#111 프로젝트 목록 읽기 api 수정
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
Labels: 💙 BE, 🐞 fix

#113 [feat] 프로젝트 파일 수정 및 삭제 기능추가
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/repository/MemberProjectRepository.java
  backend/src/main/java/com/nakaligoba/backend/repository/ProjectRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
Labels: 💙 BE, 🌟 feat, 🐞 fix

#110 feat : 스프링 시큐리티 전반 수정(#99)
  backend/src/main/java/com/nakaligoba/backend/config/SecurityConfig.java
  backend/src/main/java/com/nakaligoba/backend/controller/MemberController.java
  backend/src/main/java/com/nakaligoba/backend/filter/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/nakaligoba/backend/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/nakaligoba/backend/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/nakaligoba/backend/jwt/JwtFilter.java
  backend/src/main/java/com/nakaligoba/backend/jwt/JwtProperties.java
  backend/src/main/java/com/nakaligoba/backend/jwt/JwtProvider.java
  backend/src/main/java/com/nakaligoba/backend/service/JwtMemberDetailsService.java
  backend/src/main/java/com/nakaligoba/backend/service/MemberService.java
  backend/src/main/java/com/nakaligoba/backend/utils/JwtUtils.java
  backend/src/main/resources/application.yml
Labels: 💙 BE, 🌟 feat, ⚙️ setting, 🐞 fix

#107 feat: 채팅 구현
  backend/build.gradle
  backend/src/main/java/com/nakaligoba/backend/config/WebSocketConfig.java
  backend/src/main/java/com/nakaligoba/backend/controller/ChatController.java
  backend/src/main/java/com/nakaligoba/backend/entity/ChatMessage.java
  backend/src/main/java/com/nakaligoba/backend/repository/ChatMessageRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/ChatMessageService.java
Labels: 💙 BE, 🌟 feat, 📦 chore

#128 Console 토글 버튼 추가 및 idepage UI 수정
  frontend/src/pages/IDEPage/components/console/index.jsx
  frontend/src/pages/IDEPage/components/editor/index.css
  frontend/src/pages/IDEPage/components/editor/index.jsx
  frontend/src/pages/IDEPage/components/sidebar/index.jsx
  frontend/src/pages/IDEPage/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#120 [feat] 파일 삭제 API 추가
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
Labels: 💙 BE, 🌟 feat

#125 프로젝트 디렉터리구조 읽기
  backend/src/main/java/com/nakaligoba/backend/config/SecurityConfig.java
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/filter/CorsFilter.java
  backend/src/main/java/com/nakaligoba/backend/service/ReadProjectService.java
  backend/src/main/resources/api/file/file.yaml
Labels: 💙 BE, 🌟 feat

#129 96 re idepage project create modal UI 구현
  frontend/src/pages/IDEPage/components/file_explorer/INITIAL_TREE.jsx
  frontend/src/pages/IDEPage/components/file_explorer/index.jsx
  frontend/src/pages/IDEPage/components/modal/index.jsx
  frontend/src/pages/IDEPage/components/sidebar/index.jsx
  frontend/src/pages/IDEPage/index.jsx
  frontend/src/service/FileService.js
  frontend/src/service/projectService.js
Labels: 💜 FE, 🌟 feat, 🎨 design

#136 fix: jwt 인증시간 오류 수정
  backend/src/main/java/com/nakaligoba/backend/jwt/JwtProvider.java
Labels: 💙 BE, 🐞 fix

#134 design: invite 탭 UI 작성
  frontend/src/pages/IDEPage/components/header/components/Button.jsx
  frontend/src/pages/IDEPage/components/header/index.jsx
  frontend/src/pages/IDEPage/components/invite/index.jsx
  frontend/src/pages/IDEPage/index.jsx
Labels: 💜 FE, 🎨 design

#138 [fix] Invite API 추가 및 프로젝트 목록 불러오기 서비스 로직 수정
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/repository/MemberProjectRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
Labels: 💙 BE, 🌟 feat, 🐞 fix

#145 [fix] 초대된 인원 삭제 API 추가 및 파일 삭제 API 수정
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
Labels: 💙 BE, 🌟 feat, 🐞 fix

#148 [fix]코드 저장 오류 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/IDEPage/components/editor/index.jsx
  frontend/src/pages/IDEPage/components/file_explorer/index.jsx
  frontend/src/pages/IDEPage/components/sidebar/index.jsx
  frontend/src/pages/IDEPage/index.jsx
  frontend/src/service/FileService.js
Labels: 💜 FE, 🐞 fix

#164 refactor: JwtUtils 빈에서 static 메서드로 변경
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/service/MemberService.java
  backend/src/main/java/com/nakaligoba/backend/utils/BasicUtils.java
  backend/src/main/java/com/nakaligoba/backend/utils/JwtUtils.java
Labels: 📐 refactor
