Repository NaKaLiGoBa/WebIDE, pull requests merged in 2023-09, with the labels that each got.

#35 21 idepage header UI 구현
  frontend/src/App.css
  frontend/src/pages/IDEPage/components/editor/index.jsx
  frontend/src/pages/IDEPage/components/header/components/Button.jsx
  frontend/src/pages/IDEPage/components/header/components/ExeButton.jsx
  frontend/src/pages/IDEPage/components/header/components/ProfileBadge.jsx
  frontend/src/pages/IDEPage/components/header/index.jsx
  frontend/src/pages/IDEPage/components/header/styles.css
Labels: 💜 FE, 🌟 feat, 🎨 design

#36 [feat] BaseEntity적용 및 코드 실행 API 작성과 코드 저장,불러오기 기능 구현
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/domain/BaseEntity.java
  backend/src/main/java/com/nakaligoba/backend/entitiy/FileEntity.java
  backend/src/main/java/com/nakaligoba/backend/repository/FileRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
Labels: 💙 BE, 🌟 feat

#38 [fix] 37 filecontroller import 문제
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
Labels: 💙 BE, 🐞 fix

#40 [fix] 39 네이밍 이슈
  backend/src/main/java/com/nakaligoba/backend/entity/BaseEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
  backend/src/main/java/com/nakaligoba/backend/repository/FileRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
Labels: 💙 BE, 🐞 fix

#42 feat: cors 필터 적용
  backend/src/main/java/com/nakaligoba/backend/filter/CorsFilter.java
Labels: 💙 BE, 🌟 feat, 🐞 fix

#48 [design] idepage console,editor UI 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/IDEPage/components/console/components/CloseButton.jsx
  frontend/src/pages/IDEPage/components/console/components/Tab.jsx
  frontend/src/pages/IDEPage/components/console/index.css
  frontend/src/pages/IDEPage/components/console/index.jsx
  frontend/src/pages/IDEPage/components/editor/components/CloseButton.jsx
  frontend/src/pages/IDEPage/components/editor/components/Tab.jsx
  frontend/src/pages/IDEPage/components/editor/index.css
  frontend/src/pages/IDEPage/components/editor/index.jsx
  frontend/src/pages/IDEPage/index.jsx
Labels: 💜 FE, 🎨 design

#44 [feat] 코드 컴파일 및 빌드 후 실행
  backend/build.gradle
  backend/src/main/java/com/nakaligoba/backend/config/DockerConfig.java
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/domain/Language.java
  backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
  backend/src/main/java/com/nakaligoba/backend/service/DockerTemplate.java
  backend/src/main/java/com/nakaligoba/backend/service/RunFileService.java
  backend/src/test/java/com/nakaligoba/backend/service/RunFileServiceTest.java
Labels: 💙 BE, 🌟 feat

#47 [chore] was 도커 파일 작성
  backend/Dockerfile
Labels: 💙 BE, 🧱 devops

#49 [BE] 스프린트 1주차
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/nakaligoba/backend/BackendApplication.java
  backend/src/main/java/com/nakaligoba/backend/config/DockerConfig.java
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/domain/Language.java
  backend/src/main/java/com/nakaligoba/backend/entity/BaseEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
  backend/src/main/java/com/nakaligoba/backend/filter/CorsFilter.java
  backend/src/main/java/com/nakaligoba/backend/repository/FileRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/DockerTemplate.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
  backend/src/main/java/com/nakaligoba/backend/service/RunFileService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/nakaligoba/backend/BackendApplicationTests.java
  backend/src/test/java/com/nakaligoba/backend/service/RunFileServiceTest.java
Labels: 💙 BE

#50 [docs] 2주차 스프린트 API 명세
  .github/workflows/merge-oas.yaml
  README.md
  backend/src/main/resources/api/auth/components.yaml
  backend/src/main/resources/api/auth/signin.yaml
  backend/src/main/resources/api/auth/signup.yaml
  backend/src/main/resources/api/file/components.yaml
  backend/src/main/resources/api/file/get.yaml
  backend/src/main/resources/api/file/run.yaml
  backend/src/main/resources/api/file/save.yaml
  backend/src/main/resources/api/project/create.yaml
  backend/src/main/resources/api/project/invite.yaml
  backend/src/main/resources/api/project/run.yaml
  backend/src/main/resources/api/project/save.yaml
  backend/src/main/resources/api/project/update.yaml
  backend/src/main/resources/api/root.yaml
  docs/api/auth/signin.yaml
  docs/api/auth/signup.yaml
  docs/api/file/get.yaml
  docs/api/file/run.yaml
  docs/api/file/save.yaml
  docs/api/root.yaml
  docs/dist/swagger-initializer.js
  docs/output.yaml
Labels: ⚙️ setting, 📄 document

#52 51 스키마 작성
  backend/src/main/java/com/nakaligoba/backend/entity/ChatMessage.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/Role.java
  backend/src/main/resources/db/schema.sql
Labels: 💙 BE, 📄 document

#59 [feat] 자체 회원가입 구현
  backend/src/main/java/com/nakaligoba/backend/controller/MemberController.java
  backend/src/main/java/com/nakaligoba/backend/entity/BaseEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberEntity.java
  backend/src/main/java/com/nakaligoba/backend/repository/MemberRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/MemberService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/db/schema.sql
Labels: 💙 BE, 🌟 feat

#66 [design] 22-idepage editor UI 구현 및 스크롤 기능 추가
  frontend/src/pages/IDEPage/components/editor/components/CloseButton.jsx
  frontend/src/pages/IDEPage/components/editor/components/Tab.jsx
  frontend/src/pages/IDEPage/components/editor/index.css
  frontend/src/pages/IDEPage/components/editor/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#67 css, tabHandleClick 코드 일부수정
  frontend/src/pages/IDEPage/components/sidebar/index.jsx
Labels: 💜 FE, 🎨 design

#68 24 idepage filedirectory UI 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/IDEPage/components/file_explorer/Contextmenu.css
  frontend/src/pages/IDEPage/components/file_explorer/Contextmenu.jsx
  frontend/src/pages/IDEPage/components/file_explorer/FileSearch.jsx
  frontend/src/pages/IDEPage/components/file_explorer/Form.jsx
  frontend/src/pages/IDEPage/components/file_explorer/TabSettings.jsx
  frontend/src/pages/IDEPage/components/file_explorer/index.css
  frontend/src/pages/IDEPage/components/file_explorer/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#69 design: 46 idepage 내 run 버튼 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/IDEPage/components/editor/components/CloseButton.jsx
  frontend/src/pages/IDEPage/components/editor/components/Tab.jsx
  frontend/src/pages/IDEPage/components/editor/index.css
  frontend/src/pages/IDEPage/components/editor/index.jsx
  frontend/src/pages/IDEPage/components/header/components/Button.jsx
  frontend/src/pages/IDEPage/components/header/components/ExeButton.jsx
  frontend/src/pages/IDEPage/components/header/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#73 add: project list modal open button
  frontend/src/assets/view-list.svg
  frontend/src/pages/IDEPage/components/header/components/ProjectTitleButton.jsx
  frontend/src/pages/IDEPage/components/header/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#74 Chatroom UI 수정
  frontend/src/assets/chat-dots-fill.svg
  frontend/src/assets/send-plus.svg
  frontend/src/components/ProfileBadge.jsx
  frontend/src/pages/IDEPage/components/chatroom/component/ChatInput.jsx
  frontend/src/pages/IDEPage/components/chatroom/component/Message.jsx
  frontend/src/pages/IDEPage/components/chatroom/index.jsx
  frontend/src/pages/IDEPage/components/header/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#75 [feat] 프로젝트 파일 생성 및 목록 불러오기 API 작성
  backend/src/main/java/com/nakaligoba/backend/controller/ProjectController.java
  backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/repository/ProjectRepository.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
Labels: 💙 BE, 🌟 feat

#80 [feat] 22 idepage editor UI 수정 및 CodeMirror 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/IDEPage/components/console/index.css
  frontend/src/pages/IDEPage/components/editor/index.css
  frontend/src/pages/IDEPage/components/editor/index.jsx
  frontend/src/pages/IDEPage/index.jsx
Labels: 💜 FE, 🌟 feat, 🎨 design

#87 86 모든 requesturl 허용가능하도록 수정
  backend/src/main/java/com/nakaligoba/backend/config/SecurityConfig.java
Labels: 💙 BE, 📦 chore, 🐞 fix

#91 Swagger UI 최신화
  backend/src/main/resources/api/project/create.yaml
  backend/src/main/resources/api/project/save.yaml
  backend/src/main/resources/api/root.yaml
  docs/output.yaml
Labels: 📄 document

#92 [docs] files 테이블 생성일 수정일 추가
  backend/src/main/resources/db/schema.sql
Labels: 💙 BE, 📄 document

#94 [fix] 메타데이터 추가 및 BackendApplication.java파일에 @EnableJpaAuditing 추가
  backend/src/main/java/com/nakaligoba/backend/BackendApplication.java
  backend/src/main/java/com/nakaligoba/backend/controller/FileController.java
  backend/src/main/java/com/nakaligoba/backend/entity/FileEntity.java
  backend/src/main/java/com/nakaligoba/backend/entity/ProjectEntity.java
  backend/src/main/java/com/nakaligoba/backend/service/FileService.java
  backend/src/main/java/com/nakaligoba/backend/service/ProjectService.java
Labels: 💙 BE, 🐞 fix

#95 [fix] createat updatedat 값 자동 주입
  backend/src/main/java/com/nakaligoba/backend/BackendApplication.java
  backend/src/main/java/com/nakaligoba/backend/config/JpaConfig.java
  backend/src/main/java/com/nakaligoba/backend/entity/MemberEntity.java
  backend/src/main/java/com/nakaligoba/backend/service/MemberService.java
  backend/src/main/resources/application-test.yaml
  backend/src/test/java/com/nakaligoba/backend/config/JpaConfigTest.java
Labels: 💙 BE, 🐞 fix
